version: '3.8'
services:
  data-ingestion-service:
    image: data-ingestion-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
    networks:
      - kafka-net
networks:
  kafka-net:
    external: true